local MSG_TRIGGER = hash("trigger_response")
local MSG_COIN_COLLECT = hash("msg_coin_collect")
local MSG_DELETE_FROM_LIST = hash("entity")

go.property("spawner_url",msg.url())

function init(self)
	self.active = true
end

local function  delete_object(self, url, property)
	-- let spawner know its about to be deleted
	if (go.exists(self.spawner_url)==true) then
		msg.post(self.spawner_url, MSG_DELETE_FROM_LIST, {id=go.get_id()})
	end
	go.delete()
end

function final(self)
	
end


function on_message(self, message_id, message, sender)
	if (message_id==MSG_TRIGGER and message.enter == true and self.active==true) then
		self.active=false
	
		local pos = go.get_position()
		go.animate(".", "position.y", go.PLAYBACK_ONCE_FORWARD, pos.y+100, go.EASING_LINEAR, 0.5, 0)
		go.animate("#sprite", "tint", go.PLAYBACK_ONCE_FORWARD, vmath.vector4(0,0,0,0), go.EASING_LINEAR, 0.5, 0, delete_object)
		msg.post(msg.url("/gui#gui"),MSG_COIN_COLLECT,{value=500})
		
	end
end
